name: Backend

on:
  push:
    branches:
      - main

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@main
    with:
      enable_backend_testing: false
      enable_phpstan: true

      backend_directory: .
